### ISSUE TITLE
Doesn't seem to be working any more

### ISSUE THREAD

**Issue by catgoose** [bennypowers/template-literal-comments.nvim#1]
I don't know if there was a change to treesitter recently, but I don't get any syntax highlighting any more:

![image](https://github.com/bennypowers/template-literal-comments.nvim/assets/21010072/e8429bf9-2e25-4887-8d65-41e0755671bc)

**Comment by bennypowers** [comment]
I think this was a regression in nvim-treesitter, but I'll investigate here as well

**Comment by catgoose** [comment]
If it helps, I was able to duplicate the functionality of your plugin, though I have not tested thoroughly, by creating `queries/ecma/injections.scm` with the contents:

```scheme
; extends
(variable_declarator
  (comment) @injection.language (#offset! @injection.language 0 3 0 -3)
  (template_string) @injection.content (#offset! @injection.content 0 1 0 -1)
  )

(call_expression
  arguments: [
              (arguments
                (comment) @injection.language (#offset! @injection.language 0 3 0 -3)
                (template_string) @injection.content (#offset! @injection.content 0 1 0 -1)
                )
              ]
  ) 
```

![image](https://github.com/bennypowers/template-literal-comments.nvim/assets/21010072/263cdbdf-37c1-44fe-a73a-ba68e92b268b)

**Comment by bennypowers** [comment]
do you have the necessary parsers installed?

In the screenshot below, without changing any plugin code, I saw highlighted template literals in the temp file.

![image](https://github.com/bennypowers/template-literal-comments.nvim/assets/1466420/1a09adef-9eca-4435-ad43-6de38fcde228)

**Comment by catgoose** [comment]
Yeah I do have all the parsers installed.

I am using `NVIM v0.10.0-dev-886+gb263c73b0`

I can make it work with:

![image](https://github.com/bennypowers/template-literal-comments.nvim/assets/21010072/2fa961b6-d5a7-4fab-98f4-00ba5b16df50)

Right pane is injections.scm from your repo.

The result:

![image](https://github.com/bennypowers/template-literal-comments.nvim/assets/21010072/d407a955-125f-4d95-a70f-980575a80dc6)

**Comment by bennypowers** [comment]
ahh i see... i haven't tested on 0.10 yet
the problem with the proposed query is that it doesn't account for whitespace differences in the comment, whereas the directive and lua-match combo does

**Comment by catgoose** [comment]
Yeah I see your point.  I'll use my ecma queries in the meantime until this is fixed.  Could it be possible that the issue is how the metadata is set?  I wonder if that changed in nightly neovim.

**Comment by bennypowers** [comment]
tbh i'm probably not going to fix this until 0.10 lands in the fedora repos, but i'd be happy to review a PR before then

**Comment by catgoose** [comment]
No problem.  Can we leave this issue open until then?  I may play with this a bit and see if I can figure it out.

**Comment by catgoose** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/commit/78b54eb7f6a9956d25a3911fa0dfd0cabfe2a4c5

**Comment by bennypowers** [comment]
@catgoose can you try with https://github.com/bennypowers/template-literal-comments.nvim/pull/2?

**Comment by catgoose** [comment]
I'm having this issue again with the nightly build.  Was there another regression in treesitter?
