### ISSUE TITLE
Neovim .10 nightly: template literal comments are no longer parsed

### ISSUE THREAD

**Issue by catgoose** [bennypowers/template-literal-comments.nvim#3]
![image](https://github.com/bennypowers/template-literal-comments.nvim/assets/21010072/931e3765-8a82-4d59-8f97-67b0716076e9)

Much like #1 

Let me know if you need me to try anything.

Thanks for the plugin!

**Comment by bennypowers** [comment]
Happy to review a PR, and I'm unlikely to try this out until 0.10 is released

**Comment by catgoose** [comment]
@bennypowers  would you be able to take a look at this pretty please :1st_place_medal:

**Comment by catgoose** [comment]
Thank you!!!
